blank_issues_enabled: false
contact_links:
  - name: 💬 Discuss Ideas
    url: https://github.com/Flying-And-Robotics-Club/farlib/discussions/categories/ideas
    about: Discuss your ideas here!
  - name: Questions and Help
    url: https://github.com/Flying-And-Robotics-Club/farlib/discussions/categories/q-a
    about: Ask your questions here!